apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  annotations:
    serving.kserve.io/s3-endpoint: minio.model-storage.svc.cluster.local:9000 # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
secrets: 
  - name: s3creds